Alternative approach to previous patch
The approach in the previous patch works on Unmatched (and used to work
in the past on QEMU), but no longer.

    [..]
    ERROR: fdt fixup event failed: -22
    [..]

We used to copy it many years ago. Let's try that.

Also re-enable FDT and initrd relocation.

Signed-off-by: David Abdurachmanov <davidlt@rivosinc.com>